name: RefTrakker

org:
  hoss:
    spreadsheet:
      id: 10f4E_6B9NBZglLAVaSPqsz--z0jNcZ3ltCOIPwB7EEI
    week1: Schedule!A1:E27,Schedule!H1:L27,Schedule!O1:S27,Schedule!V1:Z27,Schedule!AC1:AG27,Schedule!AJ1:AN27,Schedule!AQ1:AU27
    week2: Schedule!A28:E54,Schedule!H28:L54,Schedule!O28:S54,Schedule!V28:Z54,Schedule!AC28:AG54,Schedule!AJ28:AN54,Schedule!AQ28:AU54
    week3: Schedule!A55:E81,Schedule!H55:L81,Schedule!O55:S81,Schedule!V55:Z81,Schedule!AC55:AG81,Schedule!AJ55:AN81,Schedule!AQ55:AU81

spring:
  datasource:
    url: jdbc:postgresql://ec2-3-214-136-47.compute-1.amazonaws.com/dfvge3198d0ojl
    username: nxieynoygcixtk
    password: fc8125b38a49dd3bc13db5f6c519ed141703f7163003a926235b9576545b4d06